version: "3.8"
services:
  mysql.mybank-app.dev:
    platform: linux/x86_64
    container_name: mybank_mysql
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "mybankapppass@@"
      MYSQL_DATABASE: mybank_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_mybank_dev:/var/lib/mysql
    networks:
      - app-network
  nginx.mybank.dev:
    container_name: mybank_nginx
    build: ./docker/images/nginx
    command: nginx -g "daemon off;"
    volumes:
      - ./:/var/www/html/mybank_app
    ports:
      - "80:80"
    links:
      - php.mybank.dev
    depends_on:
      - mysql.mybank-app.dev
    networks:
      - app-network
  php.mybank.dev:
    container_name: php.mybank.dev
    build: ./docker/images/php
    links:
      - mysql.mybank-app.dev:mysql.mybank-app.dev
    ports:
      - "9000:9000"
    expose:
      - 9000
    working_dir: /var/www/html/mybank_app
    depends_on:
      - mysql.mybank-app.dev
    volumes:
      - ./:/var/www/html/mybank_app
    networks:
      - app-network
  zookeeper:
    platform: linux/amd64
    container_name: zookeeper
    image: 'bitnami/zookeeper:latest'
    ports:
        - '2181:2181'
    environment:
        - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app-network
  kafka:
    platform: linux/amd64
    container_name: kafka
    image: 'bitnami/kafka:2.8.1-debian-10-r18'
    ports:
        - '9092:9092'
    environment:
        - KAFKA_BROKER_ID=1
        - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
        - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
        - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
        - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - app-network
    depends_on:
        - zookeeper
volumes:
  mysql_mybank_dev: {}
networks:
  app-network:
    driver: bridge
